version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3001:3001'
    command: node dist/apps/auth/main.js
    env_file:
      - .env
    networks:
      - jk-network

  blog-post:
    build:
      context: .
      dockerfile: apps/blog-post/Dockerfile
    ports:
      - '3002:3002'
    command: node dist/apps/blog-post/main.js
    env_file:
      - .env
    networks:
      - jk-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '7001:7001'
    command: node dist/apps/api-gateway/main.js
    depends_on:
      - auth
      - blog-post
    env_file:
      - .env
    environment:
      - AUTH_HOST=auth
      - BLOG_HOST=blog-post
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=blog-post
      - POOL_SIZE=10
    networks:
      - jk-network

networks:
  jk-network:
    driver: bridge
